#!/bin/bash
#Provide the subscription Id
subscriptionId=""
VMName=""
resourceGroupName=""
while getopts "hs:v:g:" arg; do
  case $arg in
    h)
      echo "usage" 
      usage
      ;;
    s)
      subscriptionId=$OPTARG
      ;;

    v)
      VMName=$OPTARG
      ;;

    g)
      resourceGroupName=$OPTARG
      ;;
    d)
      destResourceGroupName=$OPTARG
      ;;
  esac
done

if [ -z "$subscriptionId" ]   || [ -z "$VMName" ] || [ -z "$resourceGroupName" ] 
  then
  exit 1
fi
if [ -z "$destResourceGroupName" ] 
then
  destResourceGroupName=resourceGroupName
fi

#Provide the name of your resource group.
#Ensure that resource group is already created 

#Set the context to the subscription Id where Managed Disk will be created
az account set --subscription $subscriptionId
NOW="$(date +%Y%m%d-%H%M)"
LOCATION="$(az vm show --name ${VMName}  -g ${resourceGroupName} | jq  '.location'"
DISKS=$(az vm show --name  ${VMName}  -g ${resourceGroupName} | jq  '.storageProfile.dataDisks[].managedDisk.id') $(az vm show -name  ${VMName}  -g ${resourceGroupName} | jq  '.storageProfile.osDisk.managedDisk.id')"

for diskID in $DISKS; do 
  sourceDiskName="$(echo $diskID | sed 's|.*/||')"
  snapshotName="${sourceDiskName}-snap-$NOW"
 echo az snapshot create \
    -g "${resourceGroupName}" \
	--source "$diskID" \
	--name "$snapshotName"

  $(az snapshot show --name "$snapshotName" -g "${resourceGroupName}"  | jq '.id')

  #Provide the size of the disks in GB. It should be greater than the VHD file size.  
  diskSize=$(az disk show --ids $diskID | jq '.diskSizeGB')
  diskSkuName=$(az disk show --ids $diskID | jq '.sku.name')
  #diskSkuTier=$(az disk show --ids $diskID | jq '.sku.tier')
  #Provide the URI of the VHD file that will be used to create Managed Disk. 
  
  
  

  
  #If you're creating an OS disk, uncomment the following lines and replace the values
  osType='Linux' #Acceptable values are either Windows or Linux
  hyperVGeneration='v2' #Acceptable values are either v1 or v2
  
echo az disk create --resource-group $destResourceGroupName --name $diskName --sku $storageType --size-gb $diskSize --source $snapshotId

done
